### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by WSoS** [braver/isotope-ui#10]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.

```
Atom.Object.defineProperty.get (/usr/local/share/atom/resources/app/src/atom.js:55:11)
applyBackgroundColor (/home/schler_e/.atom/packages/isotope-ui/lib/config.coffee:58:13)
```

**Comment by braver** [comment]
Recent patch makes isotope fully compliant with deprecation-cop except where it improves third part packages that aren't compliant yet (e.g. zen).
