### ISSUE TITLE
Theme color selection

### ISSUE THREAD

**Issue by malexandre** [braver/isotope-ui#11]
It would be nice to be able to select the theme color. I'm not sure but I think right now it's calculated regarding the hue & other things from the current syntax background color. But one thing that's awesome with Atom is that you can overwrite that. And if I overwrite it in my `styles.less`, it's not managed by Isotope.

For example, this is the result with my background image (almost totally black): ![Screenshot](http://i.imgur.com/KbVq99l.png)
The "green on white" is not really something I like. And as you can see, I tried to overwrite your value, but I knew it wasn't working.

Keeping your way to manage all the UI colors regarding a base color but giving us the choice of the base color would be the best solution I think. For now, I'll just overwrite in the `styles.less` for the Isotope colors too.

**Comment by braver** [comment]
Yes, definitely want this. There was [this](https://discuss.atom.io/t/use-coffee-to-config-less-in-a-package/14269) discussion recently, but as concluded there, there is currently no elegant way to influence the variables that are used in LESS. 

So there's two todo's here:
- [ ] I'm working on creating better defaults, making sure contrast is good for all themes. This involves building in some contrast checks and is very much doable. Just haven't gotten around to it yet (just check the commit log: I been busy ;) ).
- [ ] Color and contrast settings [will eventually come to settings-view](https://github.com/atom/settings-view/pull/275) and when that happens I will definitely support that.

**Comment by braver** [comment]
https://github.com/atom/settings-view/pull/275 Has been closed, currently doesn't look like there's going to be a way to change less variables through config. This means there really is no way for me to realise what you're proposing: I can't get a custom color into the stylesheet.
