### ISSUE TITLE
Placeholder text in Settings uses Helvetica Neue instead of chosen Font Family

### ISSUE THREAD

**Issue by mnquintana** [braver/isotope-ui#12]
Just noticed that the placeholder text in Settings seems to be using Helvetica Neue instead of whatever Font Family is set to:

![screenshot 2015-01-27 08 41 09](https://cloud.githubusercontent.com/assets/823545/5919266/47635d84-a600-11e4-8254-541863234472.png)

**Comment by braver** [comment]
Thanks for spotting this! It's an easy fix, will probably publish a patch later today.

**Comment by braver** [comment]
fixed in 1.2.8
