### ISSUE TITLE
Code in editor is too tight to top of window

### ISSUE THREAD

**Issue by smlombardi** [braver/isotope-ui#15]
Atom .176, IsotopeUI 1.2.8 default settings

![screen shot 2015-01-29 at 1 39 05 pm](https://cloud.githubusercontent.com/assets/835148/5963684/5642ad9c-a7bc-11e4-89a6-21d8e7054c93.png)

**Comment by braver** [comment]
Yes, it kinda looks like that doesn't it. It should be the same in for instance One Dark UI though. Unlike some other themes there is no border above the editor area and it looks a bit tight. But there shouldn't be anything wrong per se (although I do agree it could look a bit better).

**Comment by braver** [comment]
I looked into it, put there is no way to put padding on that without screwing with alignment and measurements. Not sure there's anything I can do.

**Comment by smlombardi** [comment]
Not a big deal.
