### ISSUE TITLE
Two-lines overlay looks weird

### ISSUE THREAD

**Issue by vapask** [braver/isotope-ui#16]
Sometimes it is not possible to use go-to-definition overlay

![2015 01 30-19 18 47](https://cloud.githubusercontent.com/assets/797930/5978979/e04b1242-a8b4-11e4-916a-68e9781d27c4.png)

**Comment by braver** [comment]
@vapask Could you clarify what about it is not possible? Does it not work? Is there a layout issue? What I'm seeing is that sometimes the definition name is too long and the line number will scroll out of view.

**Comment by vapask** [comment]
It works, but it is useless.

for example ctrl+r in big file:
![2015 01 30-21 28 42](https://cloud.githubusercontent.com/assets/797930/5980981/003fa52e-a8c7-11e4-823b-83090fcbbf6d.png)

if I set `.list-group li` height to auto, `.first-line, .second-line` display to block, then it looks like this:
![2015 01 30-21 33 38](https://cloud.githubusercontent.com/assets/797930/5981041/adbb5a04-a8c7-11e4-9cea-5b3b8eabf62c.png)
which is much more useful

**Comment by braver** [comment]
Oh, right, that _is_ obvious then. This isn't covered in the style guide so I didn't catch that before. Thanks for reporting, I'll look into a fix.

**Comment by braver** [comment]
Fixed in https://github.com/braver/isotope-ui/commit/31a33a746bd4b19bece9654a4ec1269678cd415e and will be released this weekend.

**Comment by vapask** [comment]
Awesome! Thank you.
