### ISSUE TITLE
Treeview items don't have color when in focus

### ISSUE THREAD

**Issue by Nxt3** [braver/isotope-ui#17]
If you're in a project, open the treeview. Then press `ctrl+0`. This will put the treeview into focus to allow for other actions (such as adding a new file, `ctrl+a`). Just press `ctrl+0` multiple times; there is no indication that the treeview is in focus. This is a ui-themed element, and no matter what syntax theme I use, there is no color applied.

**Comment by braver** [comment]
You're right, the focussed state is not visible. Thanks for reporting, fixed it!

**Comment by Nxt3** [comment]
Thank you!
