### ISSUE TITLE
Add active pane indicator

### ISSUE THREAD

**Issue by mnquintana** [braver/isotope-ui#18]
One of the nice things I noticed was added in One Dark / Light UI is that there's an indicator for which pane is active if you have multiple panes open:

![image](https://cloud.githubusercontent.com/assets/823545/6012512/f0d12296-ab16-11e4-9155-41bcb69f263b.png)
(ie. the bright blue bar on the right tab in this screenshot)

Right now there's no way of telling which tab is active other than by hunting for your cursor / the current line.

**Comment by braver** [comment]
Thanks for reporting, hadn't noticed this but it's an easy fix.
