### ISSUE TITLE
Wide theme variant

### ISSUE THREAD

**Issue by vapask** [braver/isotope-ui#22]
Could you please return less compact theme variant and config option? I prefer previous default look and feel

**Comment by braver** [comment]
@vapask In the recent update three things got more compact:
- tabs
- status bar
- tree-view

Would you be happy with just more spacious tabs and statusbar? Or would your prefer also a more spacious tree-view?

**Comment by vapask** [comment]
I want all of this things to be more spacious, but if I should choose, here are things in order of priority: tabs, tree-view, status bar.

**Comment by braver** [comment]
Ok, duly noted. Tree-view is super complicated already though, which was my main reason for taking the option out. There are variables in the stylesheets that make it easy to change the spacing, but right now it's impossible to manipulate them from the config. Core Atom team is working on that though, so more flexibility will surely come in the future.

So, anyway, I'll look into a short-term solution. Long-term, this is definitely coming back.

**Comment by braver** [comment]
@vapask FYI, theme config via core has been killed, so I'm not waiting for that. I'm currently testing bringing back a "spacious" option, will release tomorrow or the day after.

**Comment by vapask** [comment]
thank you for your efforts

**Comment by braver** [comment]
fixed in https://github.com/braver/isotope-ui/commit/1534b62d09c5af176955bc90d82e9de1be8b0666
