### ISSUE TITLE
Seamless tabs

### ISSUE THREAD

**Issue by simurai** [braver/isotope-ui#24]
Just FYI: Tabs now have a `data-type` attribute. For example text editor tabs have `data-type="TextEditor"`.

This way only `<atom-text-editor>` tabs could use a Syntax theme's background color when active, but other panes, like settings could have a different active color to make them more seamless.

![screen shot 2015-02-12 at 12 11 09 pm](https://cloud.githubusercontent.com/assets/378023/6161167/4c2755f2-b2b0-11e4-8cf2-cd257608ef0f.png)

![screen shot 2015-02-12 at 12 10 20 pm](https://cloud.githubusercontent.com/assets/378023/6161168/5450d0f0-b2b0-11e4-838f-bc7d05bf6ddf.png)

**Comment by braver** [comment]
Oh wow, thanks, that is so awesome!

**Comment by braver** [comment]
implemented in https://github.com/braver/isotope-ui/commit/10d1de56c528a3f172096061de46b7f641f0085f
