### ISSUE TITLE
Use the `atom-workspace` tag instead of the `workspace` class.

### ISSUE THREAD

**Issue by rogeriopvl** [braver/isotope-ui#27]
In index.less: Use the `atom-workspace` tag instead of the `workspace` class.

I'm getting this warning on Atom. Although I haven't found any occurrence of the `.workspace` class in the less files of the project.

Not sure why this is happening.

**Comment by braver** [comment]
Thanks for reporting. There was one selector left for a tweak in web-browser. I resolved that last night: https://github.com/braver/isotope-ui/commit/cb72cf43531e987588415924c4a7c2a276e66e49
