### ISSUE TITLE
Logs showing in ftp file tree

### ISSUE THREAD

**Issue by petr24** [braver/isotope-ui#28]
When using Isotope which I love as a theme. I use a package called Remote FTP and when I connect to a server I see logs for accessing the server. Image attached. I found this class in the dev tools ".tool-panel.tool-panel" and just set the color opacity to 0, and now I can't see them anymore. 
![screen shot 2015-02-12 at 2 02 06 pm](https://cloud.githubusercontent.com/assets/3904464/6174905/488b8a02-b2c0-11e4-94ae-399f755e06e7.png)

**Comment by braver** [comment]
There was a stray `position: relative` in isotope that screwed up the log display in that package. Fixed it, will roll out an update somewhere the coming days.

**Comment by petr24** [comment]
Cool man, keep up the good work! Doing great stuff.
