### ISSUE TITLE
Tree view always shows scrollbar

### ISSUE THREAD

**Issue by celsomiranda** [braver/isotope-ui#3]
The tree view appears to always be about 20px longer than it should, always showing a scroll bar as a result.

Included pic for reference:
![isotope-ui](https://cloud.githubusercontent.com/assets/769237/5695478/65c7e830-999e-11e4-94f4-54cd09662d84.JPG)

Using Atom 0.169.0 on Windows 8 x64.

**Comment by braver** [comment]
@celsomiranda I just pushed 1.0.4 that fixes this. Thanks for reporting!

**Comment by celsomiranda** [comment]
Thank you @braver, for the quick response and bugfix.
