### ISSUE TITLE
Background image doesn't work

### ISSUE THREAD

**Issue by cbdavide** [braver/isotope-ui#30]
Hi, I have the Background Image option selected, with the default image, but it doesn't set any background image.

![dd](https://cloud.githubusercontent.com/assets/5614801/6204387/3639423c-b517-11e4-92d2-7593e26e79cb.png)

**Comment by braver** [comment]
Hi @cbdavide, thanks for reporting. I could be wrong, but your version of Atom seems to be behind a number of key releases. Could you check that? Also, I'd be interested to know if there is any information in the console.

**Comment by cbdavide** [comment]
Ohh! men, I'm sorry, it was the version of Atom, everything works fine!
Sorry for the inconvenient.

**Comment by cbdavide** [comment]
Ohh! men, I'm sorry, it was the version of Atom, everything works fine!
Sorry for the inconvenient.
