### ISSUE TITLE
Disable animation on tooltip

### ISSUE THREAD

**Issue by svsudhir** [braver/isotope-ui#31]
Well, this is not an issue with the theme but request for some guidance and support.

With the isotope-ui in Atom editor when you hover on a file name in a Tab, the Tooltip containing full path name of the file appears after a brief delay with an animation motion from left top to right. I notice that this class is getting assigned "tooltip fade bottom in" to the div.

I wish to disable the animation, or make it just fade in without any delay.  I examined the styles folder but could not locate where you are setting this animation. Please guide how to disable the animation of the tooltip.

Thanks for a really cool theme.
SVS

**Comment by braver** [comment]
The animation is not part of my theme but just uses the default. If you just want to disable the animation, you can add this to your stylesheet:

```
.tooltip { transition: none; }
```

The delay is actually not part of the css transition, but I think it's done somewhere in the core javascript. If you want to know how to take out the delay I would suggest posting a question [here](https://discuss.atom.io), someone should be able to get you started.
