### ISSUE TITLE
When using split view, only the focused tab is highlighted

### ISSUE THREAD

**Issue by mik01aj** [braver/isotope-ui#34]
Imho the marked tab should be highlighted too.

![screenshot 2015-03-10 16 18 49](https://cloud.githubusercontent.com/assets/3027415/6577909/528031c6-c741-11e4-88cf-5f8c3d92acd9.png)

**Comment by braver** [comment]
This is intentional, but I think you're right: it should also be obvious which tab belongs to the editor that isn't focussed. Will look into it!
