### ISSUE TITLE
Tabs overflow instead of shrinking to fit

### ISSUE THREAD

**Issue by feens** [braver/isotope-ui#35]
I noticed that recently Isotope seems to be ignoring the Tab Scrolling setting, and just always scrolls (which I personally dislike).

**Comment by braver** [comment]
The "tab scrolling" option toggles flipping through open tabs by scrolling: scrolling up and down moves you left and right through open tabs.
This setting is respected by Isotope.

I think you mean that when there are too many tabs open, in Isotope you can scroll left and right to reach tabs that no longer fit the screen. I believe this is preferable over having the tabs become (at some point) only a few pixels wide.

**Comment by feens** [comment]
My bad on the wrong interpretation of that tabs setting.  However, personally, I hate having tabs disappear from my view, as then I don't notice them being open (and I find the act of having to scroll through the tab bar to be very clunky).  Is there any way to have this as a setting?  Otherwise it means I'll have to a) either hack/fork the theme, or b) switch to another theme.  Also, the default behaviour on OS X is to shrink the tabs, not to scroll, so that also remains the "standard" behaviour.  

I realize having squished, unreadable tabs is also not great, though I think it's just a trade-off of tabbed interfaces.

**Comment by braver** [comment]
Well you can always put something like

``` css
.tab-bar .tab {
  min-width: 16px;
}
```

in your stylesheet. It's a world of trade-offs and there are a number of reasons this is (for now at least) what I ended up with for this theme. Perhaps I need to revisit this... I'll sleep on it ;)

**Comment by braver** [comment]
The latest release shrinks tabs much further than it used to, and I changed some things around to solve some issues I had with tiny tabs. At some point they'll stop shrinking and start scrolling though, there are only so many pixels to go around.
