### ISSUE TITLE
What are the syntax themes of the first and second screenshots ?

### ISSUE THREAD

**Issue by haggen** [braver/isotope-ui#41]
I'm sorry but I'm dying to know. :P

**Comment by braver** [comment]
:+1: The first is [Duo-Tone-Dark](https://atom.io/themes/duotone-dark-syntax), the second is [Solarized Light](https://atom.io/themes/solarized-light-syntax).

**Comment by RangerMauve** [comment]
Also, what is the third one? It looks like some sort of monokai variant.

**Comment by braver** [comment]
I think it's this one: https://atom.io/themes/monokai

**Comment by RangerMauve** [comment]
Thanks!
