### ISSUE TITLE
Where do I define custom settings

### ISSUE THREAD

**Issue by jchannon** [braver/isotope-ui#43]
Sorry for the noob question but I'm new to Atom where do I configure and what are the values I set for the options in this theme?

**Comment by braver** [comment]
They’re working on making this more obvious. You should be able to go to settings, themes, open the theme, and there should be a bunch of options there.

**Comment by jchannon** [comment]
In the UI Theme dropdown I chose Isotope but I don't see any options

![screen shot 2015-05-08 at 10 22 49](https://cloud.githubusercontent.com/assets/105126/7533765/367a7a96-f56c-11e4-8b37-00b5db8df23c.png)

**Comment by braver** [comment]
If you scroll down a bit you should see this:
![screen shot 2015-05-08 at 11 31 52](https://cloud.githubusercontent.com/assets/2543659/7533939/e49fc03c-f575-11e4-84b6-083b90d0b9df.png)

**Comment by jchannon** [comment]
Thanks!
