### ISSUE TITLE
Custom file icons?

### ISSUE THREAD

**Issue by JamesCoyle** [braver/isotope-ui#46]
Would there be any chance of you adding custom icons for each file type? That is the only thing missing from this theme for me. Even something as simple as a maximum three character representation such as: `<>` for HTML; `CSS`; `JS`; `PHP`; `{}` for JSON; `XML`; `C`; `C#`; `C++`; `PY` etc. would really help to identify files much quicker.

**Comment by braver** [comment]
Look for the file icons package. That should be compatible, and it's much better to have it in a separate package.

**Comment by JamesCoyle** [comment]
Ah didn't think of that. I've seen a few themes that came with icons so kinda assumed it was a theme specific thing I guess. Thanks.

**Comment by braver** [comment]
Yeah, some opt to include it in the theme, but the file icons package has its own maintainers, so that's a much more powerful way to go.
