### ISSUE TITLE
It won't work for me.

### ISSUE THREAD

**Issue by TheConArtistHD** [braver/isotope-ui#47]
I do the settings and everything but it won't work. I even go to the themes area and check UI and it's not there.

**Comment by braver** [comment]
I'm sorry something seems to not work on your system, but I need more information. What are you trying to do, which steps do I need to take to reproduce this, what version of atom, isotope-ui and other packages are you running, on what kind of system?

**Comment by TheConArtistHD** [comment]
Okay, so I fixed it. For some reason I had to restart my PC or something. I
then went in and reinstalled Isotope-ui. Looks good now. Thanks for the
concern you had.
