### ISSUE TITLE
Missing directories state icons

### ISSUE THREAD

**Issue by stormherz** [braver/isotope-ui#54]
Hi!

First of all - thanks a lot for a great UI theme, that's practically one of the two themes for Atom which I can actually use and I'm really happy with it.
The only thing is bothering me - currently, directories state icons (opened, closed) are either non visible or not supported, maybe. As you can see in the attached screenshot - there is no distinction between opened directory icon and closed one. Not a big deal, actually, but I was wondering is there any plans to change it in future releases? Or maybe something is wrong with my configuration?

Thanks in advance!

![isotope_directories](https://cloud.githubusercontent.com/assets/235075/12355147/8c0fb6b2-bbbc-11e5-80a0-eea11a1c36f3.png)

**Comment by braver** [comment]
Hi, glad you like the theme! Nothing wrong with your setup, there is no indication in the icon and there hasn't ever been one unless my memory fails me. In fact the icon set used ([octicons](https://octicons.github.com)) doesn't have an "open folder" icon. The official themes use additional chevron icons but I never thought it necessary.

**Comment by stormherz** [comment]
@braver ah, I see, thanks. Then I guess it's cleaner that way =)
