### ISSUE TITLE
Deprecated selector in `isotope-ui/index.less`

### ISSUE THREAD

**Issue by ccournoyer-oktane** [braver/isotope-ui#55]
In `isotope-ui/index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor .ui-site-1,
atom-text-editor::shadow .ui-site-1` => `atom-text-editor .ui-site-1,
atom-text-editor.editor .ui-site-1`

* `atom-text-editor .ui-site-1 .text-subtle,
atom-text-editor::shadow .ui-site-1 .text-subtle` => `atom-text-editor .ui-site-1 .text-subtle,
atom-text-editor.editor .ui-site-1 .text-subtle`

* `atom-text-editor .ui-site-2,
atom-text-editor::shadow .ui-site-2` => `atom-text-editor .ui-site-2,
atom-text-editor.editor .ui-site-2`

* `atom-text-editor .ui-site-2 .text-subtle,
atom-text-editor::shadow .ui-site-2 .text-subtle` => `atom-text-editor .ui-site-2 .text-subtle,
atom-text-editor.editor .ui-site-2 .text-subtle`

* `atom-text-editor .ui-site-3,
atom-text-editor::shadow .ui-site-3` => `atom-text-editor .ui-site-3,
atom-text-editor.editor .ui-site-3`

* `atom-text-editor .ui-site-3 .text-subtle,
atom-text-editor::shadow .ui-site-3 .text-subtle` => `atom-text-editor .ui-site-3 .text-subtle,
atom-text-editor.editor .ui-site-3 .text-subtle`

* `atom-text-editor .ui-site-4,
atom-text-editor::shadow .ui-site-4` => `atom-text-editor .ui-site-4,
atom-text-editor.editor .ui-site-4`

* `atom-text-editor .ui-site-4 .text-subtle,
atom-text-editor::shadow .ui-site-4 .text-subtle` => `atom-text-editor .ui-site-4 .text-subtle,
atom-text-editor.editor .ui-site-4 .text-subtle`

* `atom-text-editor .ui-site-5,
atom-text-editor::shadow .ui-site-5` => `atom-text-editor .ui-site-5,
atom-text-editor.editor .ui-site-5`

* `atom-text-editor .ui-site-5 .text-subtle,
atom-text-editor::shadow .ui-site-5 .text-subtle` => `atom-text-editor .ui-site-5 .text-subtle,
atom-text-editor.editor .ui-site-5 .text-subtle`

* `atom-text-editor.mini,
atom-text-editor.mini::shadow` => `atom-text-editor.mini,
atom-text-editor.mini.editor`

* `atom-text-editor.mini .placeholder-text,
atom-text-editor.mini::shadow .placeholder-text` => `atom-text-editor.mini .placeholder-text,
atom-text-editor.mini.editor .placeholder-text`

* `atom-text-editor.mini .selection .region,
atom-text-editor.mini::shadow .selection .region` => `atom-text-editor.mini .selection .region,
atom-text-editor.mini.editor .selection .region`

* `atom-text-editor.mini .cursor,
atom-text-editor.mini::shadow .cursor` => `atom-text-editor.mini .cursor,
atom-text-editor.mini.editor .cursor`

* `atom-text-editor.mini .markup.underline,
atom-text-editor.mini::shadow .markup.underline` => `atom-text-editor.mini .markup.underline,
atom-text-editor.mini.editor .syntax--markup.syntax--underline`

* `atom-text-editor.mini.is-focused,
atom-text-editor.mini.is-focused::shadow` => `atom-text-editor.mini.is-focused,
atom-text-editor.mini.is-focused.editor`

* `atom-text-editor.mini.is-focused .selection .region,
atom-text-editor.mini.is-focused::shadow .selection .region` => `atom-text-editor.mini.is-focused .selection .region,
atom-text-editor.mini.is-focused.editor .selection .region`

* `atom-text-editor.mini.is-focused .placeholder-text,
atom-text-editor.mini.is-focused::shadow .placeholder-text` => `atom-text-editor.mini.is-focused .placeholder-text,
atom-text-editor.mini.is-focused.editor .placeholder-text`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by xeron** [comment]
@braver hi, any plans on new release with this fix?

**Comment by braver** [comment]
Hm, guess I overlooked that. 2.8.0 is out now! @alistairholt also feel free to `apm publish` any time you want.
