### ISSUE TITLE
`Snippets: Available` does not render correctly

### ISSUE THREAD

**Issue by despairblue** [braver/isotope-ui#6]
There should probably be a space between the snippet starter and the snippet name.

By the way: Amazing work you did with this theme!

![ss](https://cloud.githubusercontent.com/assets/927609/5740259/fed62ca2-9c01-11e4-8ebd-2b96f1c49519.png)
## Versions
- **Atom:**       0.172.0
- **Atom-Shell:** 0.20.5
- **OS:**         linux 3.14.26-1-lts
- **Misc**
  - apm  0.119.0
  - npm  1.4.4
  - node 0.10.35
  - python 3.4.2
  - git 2.2.2

---

<small>This report was created in and posted from the Atom editor using the package `bug-report` v0.5.3.</small>

**Comment by braver** [comment]
Thanks for reporting this, and for the compliment. I will look into it later today.
