### ISSUE TITLE
Fonts change size upon restart.

### ISSUE THREAD

**Issue by CodeAmend** [braver/isotope-ui#60]
I can reproduce the bug like this:

1) Select Atom Material UI.
2) Select Isotop UI

we notice the fonts are a similar size to Atom Material.

3) exit Atom
4) start Atom back up: fonts are really small.

Of course I can edit the style sheet, but this should not happen.

Also, menu selector drop downs are VERY small. Can I change just these?

**Comment by alistairholt** [comment]
I tried to reproduce this using the steps you provided but I was unable to. Can you show us your `styles.less` file?

**Comment by CodeAmend** [comment]
There is nothing, I havn't started hacking yet.

**Comment by alistairholt** [comment]
Can you provide us with your OS platform and version, Atom version and isotope-ui version?

**Comment by CodeAmend** [comment]
Interesting that I cannot reproduce anymore. I have updated since then. Thank you for your time, if I get the error again, I will note those versions and respond.
