### ISSUE TITLE
Tree view Horizontal scrolling not working.

### ISSUE THREAD

**Issue by ddaza** [braver/isotope-ui#61]
The tree horizontal scroll suddenly broke in the latest version of atom v1.17.0.  Other themes work normally but this theme cuts the content and wont let me scroll.

**Comment by braver** [comment]
Yeah, this theme is basically deprecated by now. So many new features and massive changes like the docs api, I can't keep up with it. Feel welcome to submit a PR, but if it's up to me I don't think this is going anywhere.

**Comment by ddaza** [comment]
Oh man! That's so sad to hear 😢  this is the only theme that doesn't hurt my eyes.
I'll try to give a crack at it and PR something.

**Comment by alistairholt** [comment]
I'm still interested in maintaining this theme so I'll take a look at this when I get a chance.

**Comment by braver** [comment]
Oh sure, definitely! Much appreciated too. Just another illustration of how up to date I am on this 😞 I'll leave you guys to it and if you need anything let me know.

**Comment by alistairholt** [comment]
@ddaza you should find this is now fixed in the latest version (2.8.3).

**Comment by ddaza** [comment]
nice! 😄
