### ISSUE TITLE
Autocomplete background not expanding

### ISSUE THREAD

**Issue by plttn** [braver/isotope-ui#7]
![Screenshot or GIF movie](https://lh6.googleusercontent.com/-IAVHxOW86JE/VLcDyn1c_pI/AAAAAAAAQIA/5ivcFjt15h8/s0/2015-01-14_16-03-26.png)

Autocomplete Plus background box is not expanding to the text given. Might be an issue with that package handling different lineheights though.
## Versions
- **Atom:**       0.172.0
- **Atom-Shell:** 0.20.5
- **OS:**         Microsoft Windows 8.1 Pro
- **Misc**
  - apm  0.119.0
  - npm  1.4.4
  - node 0.10.35
  - python 2.7.8
  - git 1.9.5.msysgit.0
  - visual studio 2013

---

<small>This report was created in and posted from the Atom editor using the package `bug-report` v0.5.3.</small>

**Comment by braver** [comment]
@plttn thanks for reporting. I'm taking this up with autocomplete-plus, I think their layout is causing this issue and is best resolved on their end. I will patch it in isotope if that doesn't work or takes too long, but we'll see.

**Comment by braver** [comment]
@plttn I don't know what did it (many changes all over the place including core) but I can't reproduce this anymore. Can you verify?

**Comment by plttn** [comment]
Still reproing for me.

Weird.

**Comment by braver** [comment]
Alright, I got it. Patch will come to the theme later this weekend. Thanks!
