### ISSUE TITLE
Settings are gone

### ISSUE THREAD

**Issue by olmokramer** [braver/isotope-ui#9]
Hey I just updated your theme to `v1.1.3` from the settings view, and now there are no more settings to adjust. Restarting Atom didn't work. I then tried to uninstall the package, and install it again from the settings view, but still no luck. It didn't seem to matter whether your package was activated or not.

I'm on Atom `v0.174.0` on Linux Debian 8.

**Comment by braver** [comment]
You mean there are no settings for Isotope?
What happens when you reload atom (View > Reload)?
I'm looking into it anyway.

**Comment by olmokramer** [comment]
Yeah that's what i meant.

I found them again though. I have to set the theme as active theme, then restart Atom. <i>Then</i> there are settings to adjust. I didn't do both things before...

**Comment by braver** [comment]
Ok, I can reproduce this. I think Atom is not running the theme's coffee unless the theme is activated (which makes sense), so it doesn't read the config definition (which is inconvenient).

**Comment by olmokramer** [comment]
Too bad... Nothing you can do I guess. Probably some startup speed improvements over at Atom. I could've sworn it didn't behave this way back when I tried the first release of isotope-ui on an older version of Atom...

**Comment by braver** [comment]
Feels to me to be new. I've tried graphite-ui which has a setting as well, and it behaves the same. I would also have sworn that previously I've been able to access those settings before. 

Anyway, thanks for reporting. I will take it up with the core team to figure out if this is a regression or if anything can be done.

**Comment by olmokramer** [comment]
Good to know that my memory is not failing me :smile:

**Comment by braver** [comment]
I'm closing this: I recently refactored the way coffee is being run in isotope and it's doing everything the API allows. That's all I can do right now... You can watch https://github.com/atom/settings-view/issues/347 to see when core improvements come through to improve settings for themes.
